### ISSUE TITLE
Failure to translate keys

### ISSUE THREAD

**Issue by ghost1372** [MartinKuschnik/Goji#5]
I have a strange problem, first of all, not all keys are translated. As you can see, the red box has been translated but the orange box has not been translated
![Untitled2](https://user-images.githubusercontent.com/9213496/113564439-a36dcf00-961e-11eb-8099-b5216fd647e7.png)

second, language cant change when application is staring

`            Language = XmlLanguage.GetLanguage("fa");
`

I attached the sample program, please take a look
[HandySub.zip](https://github.com/MartinKuschnik/Goji/files/6257684/HandySub.zip)

**Comment by MartinKuschnik** [comment]
Hi @ghost1372 

the first problem is that the dependency property `LocalizationProperties.TranslationProvider` is not inhered to the `NavigationViewItem` entries. Its hard to understand why because I do not know the modernwpf framework.

A workaround would be to set the `TranslationProvider` for each Item like the following code shows:

```xaml
<ui:NavigationViewItem IsSelected="True" Tag="Subscene" Content="{DynamicTranslation Subscene}" 
    LocalizationProperties.TranslationProvider="resx://HandySub;HandySub.Assets.Strings.Lang">
	<ui:NavigationViewItem.Icon>
		<ui:PathIcon Data="{DynamicResource SubtitleGeometry}"/>
	</ui:NavigationViewItem.Icon>
</ui:NavigationViewItem>
```

Can you please explain the second point a bit more?

**Comment by ghost1372** [comment]
oh thank you, It makes sense.
I meant the program language does not change in OnStartup Method.
It does not matter, I think the explanation you gave will solve the problem.
